server:
  port: 8888
sourceDatabase:
  host:
  port:
  user:
  password:
  useSshTunnel:
  sshHost:
  sshPort:
  sshUser:
  sshPassword:
targetDatabase:
  host:
  port:
  user:
  password:
  useSshTunnel:
  sshHost:
  sshPort:
  sshUser:
  sshPassword: