server:
  port: 8888
sourceDatabase:
  host: 4509o1t863.zicp.vip
  port: 41274
  user: ytzl
  password: ytzl
  useSshTunnel: false
  sshHost:
  sshPort:
  sshUser:
  sshPassword:
targetDatabase:
  host: localhost
  port: 3306
  user: pigx
  password: pigx
  useSshTunnel: true
  sshHost: 106.52.249.252
  sshPort: 22
  sshUser: root
  sshPassword: Admin@123.